---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.42.42"}]

provisioner:
  name: policyfile_zero

platforms:
  - name: ubuntu-14.04
    driver:
      box: moto/bt-base

suites:
  - name: default
    data_bags_path: "./data_bags"
    encrypted_data_bag_secret_key_path: "/etc/chef/encrypted_data_bag_secret"
    run_list:
      - recipe[ipboard_proxy::default]
    attributes:
